<a href="https://colab.research.google.com/github/mohdsaad379/MachineLearning/blob/main/KNNalgorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [206]:
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import random

In [207]:
iris_data=datasets.load_iris()

In [208]:
print(iris_data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [209]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [213]:
iris_data1=pd.DataFrame(iris_data.data)
# iris_data1=np.array(iris_data1)
iris_data1
iris_data2=pd.DataFrame(iris_data.target)
# iris_data2=np.array(iris_data2)

In [214]:
iris_dataFrame=pd.concat([iris_data1,iris_data2],axis=1)
iris_dataFrame

0    1    2    3  0
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

In [216]:
iris_dataFrame=np.array(iris_dataFrame)

In [80]:
def loadDataset(split,trainingSet=[],testingSet=[]):
  for i in range(len(iris_dataFrame)):
    dataset=iris_dataFrame.iloc[i]
    if random.random()<split:
      testingSet.append(np.array(dataset))
    else:
      trainingSet.append(dataset)

    


In [197]:
training_set=[]
testing_set=[]
loadDataset(0.1,training_set,testing_set)

In [198]:
len(training_set)

131

In [166]:
import math
def euclideanDistance(instance1,instance2,length):
  distance=0
  for x in range(length):
    distance+=pow((instance1[x]-instance2[x]),2)
  return math.sqrt(distance)

In [167]:
data1=[2,2,2,0]
data2=[4,4,4,1]
distance=euclideanDistance(data1,data2,3)
print('Distance :'+repr(distance))

Distance :3.4641016151377544


In [168]:
import operator
def getNeighbors(trainingSet,testInstance,k):
  distances=[]
  length=len(testInstance)-1
  for x in range(len(trainingSet)):
    dist=euclideanDistance(testInstance,trainingSet[x],length)
    distances.append((trainingSet[x],dist))
  distances.sort(key=operator.itemgetter(1))
  neighbors=[]
  for i in range(k):
    neighbors.append(distances[x][0])
  return neighbors

In [169]:
testInstance1=[[0.2,0.1,0.3,0.2,1]]
getNeighbors(trainingSet=training_set,testInstance=testInstance1,k=3)

[0    5.9
 1    3.0
 2    5.1
 3    1.8
 0    2.0
 Name: 149, dtype: float64, 0    5.9
 1    3.0
 2    5.1
 3    1.8
 0    2.0
 Name: 149, dtype: float64, 0    5.9
 1    3.0
 2    5.1
 3    1.8
 0    2.0
 Name: 149, dtype: float64]

In [170]:
def getResponse(neighbors):
  classVotes={}
  for x in range(len(neighbors)):
    response=neighbors[x][-1]
    if response in classVotes:
      classVotes[response]+=1
    else:
      classVotes[response]=1
  sortedVotes=sorted(classVotes.items(),key=operator.itemgetter(1),reverse=True)
  return sortedVotes[0][0]  
np.array(testing_set).shape
testing_set[1]

array([5. , 3.6, 1.4, 0.2, 0. ])

In [199]:
predictions=[]
for i in range(len(testing_set)):
  test_temp=testing_set[i].reshape(1,-1)
  test_temp=test_temp[:,:4]
  neighbors=getNeighbors(trainingSet=training_set,testInstance=test_temp,k=3)
  predictions.append(getResponse(np.array(neighbors)))
  print("prediction : "+str(predictions[i])+"  Actual : "+str(testing_set[i][-1]))

prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0


In [192]:
def getAccuracy(testSet,predictions):
  correct=0
  for x in range(len(testSet)):
    if testSet[x][-1] is predictions[x]:
      correct+=1
  return (correct/float(len(testSet)))*100.0

In [193]:
for i in range(len(testing_set)):
  print("prediction : "+str(predictions[i])+"  Actual : "+str(testing_set[i][-1]))
  

prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 0.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 1.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
prediction : 2.0  Actual : 2.0
predicti

In [194]:
training_set1=[[2,2,2,'a'],[10,10,10,'b'],[5,5,5,'a']]
neighbors=getNeighbors(trainingSet=training_set1,testInstance=[[4,4,4]],k=3)
print(neighbors)

[[5, 5, 5, 'a'], [5, 5, 5, 'a'], [5, 5, 5, 'a']]


In [203]:
from sklearn.neighbors import KNeighborsClassifier

In [217]:
X_train,X_test,Y_train,Y_test=train_test_split( iris_dataFrame[:,:4], iris_dataFrame[:,-1], test_size=0.33, random_state=42)

In [219]:
model=KNeighborsClassifier(n_neighbors=3)
model=model.fit(X_train,Y_train)

In [231]:
test=[[5.1, 3.5, 1.4, 0.2]]

model.predict(test)

array([0.])