<a href="https://colab.research.google.com/github/mohdsaad379/MachineLearning/blob/main/naiyes_bayersAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import csv
import numpy as np
import math
import random
from sklearn import datasets
import pandas as pd

In [16]:
data=datasets.load_diabetes()
input=pd.DataFrame(data.data)
output=pd.DataFrame(data.target)
data_dataFrame=pd.concat([input,output],axis=1)
data_dataFrame=np.array(data_dataFrame)
len(data_dataFrame)

442

In [52]:
trainSize=int(len(data_dataFrame)*0.8)
trainSet=[]
testSet=[]
copy=data_dataFrame
for i in range(len(data_dataFrame)):
  if random.random()<0.8:
    trainSet.append(data_dataFrame[i])
  else:
    testSet.append(data_dataFrame[i])


In [53]:
print(len(trainSet))

352


In [23]:
def separateByClass(data_dataFrame):
  separated={}
  for i in range(len(data_dataFrame)):
    vector=data_dataFrame[i]
    if vector[-1] not in separated:
      separated[vector[-1]]=[]
    separated[vector[-1]].append(vector)
  return separated

In [25]:
def mean(numbers):
  return sum(numbers)/float(len(numbers))

In [27]:
def stddev(numbers):
  avg=mean(numbers)
  variance=sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
  return math.sqrt(variance)

In [33]:
def summarize(dataset):
  summaries=[(mean(attribute),stddev(attribute)) for attribute in zip(*dataset)]
  del summaries[-1]
  return summaries

In [60]:
def summarizeByClass(dataset):
  separated=separateByClass(dataset)
  # print(separated)
  summaries={}
  for classValues,instances in separated.items():
    summaries[classValues]=summarize(instances)
  return summaries

In [73]:
def calculateProbability(x,mean,stddev):
  exponent=math.exp(-(math.pow(x-mean,2)/(1+2*math.pow(stddev,2))))
  return (1/(1+math.sqrt(2*math.pi)*stddev))*exponent

In [41]:
def calculateClassProbabilities(summaries,inputVector):
  probabilities={}
  for classValues, classSummaries in summaries.items():
    probabilities[classValues]=1
    for i in range(len(classSummaries)):
      mean,stddev=classSummaries[i]
      x = inputVector[i]
      probabilities[classValues]*= calculateProbability(x,mean,stddev)
  return probabilities

In [43]:
def predict(summaries, inputVector):
  probabilities=calculateClassProbabilities(summaries,inputVector)
  bestLabel,bestProb=None, -1
  for classValues, probability in probabilities.items():
    if bestLabel is None or probability> bestProb:
      bestProb=probability
      bestLabel=classValues
  return bestLabel

In [63]:
def getPredictions(summaries,testSet):
  predictions=[]
  for i in (range(len(testSet))):
    result=predict(summaries,testSet[i])
    predictions.append(result)
  return predictions

In [47]:
def getAccuracy(testSet,predictions):
  correct=0
  for x in range(len(testSet)):
    if testSet[i][-1]==predictions[x]:
      correct+=1
  return (correct/float(len(testSet)))*100

In [ ]:
summaries=summarizeByClass(trainSet)
predictions=getPredictions(summaries,testSet)
accuracy=getAccuracy(testSet,predictions)
print("accuracy {0}%".format(accuracy))

**SKLEARN**


In [76]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [77]:
dataset=datasets.load_iris()


In [78]:
model=GaussianNB()
model.fit(dataset.data,dataset.target)

GaussianNB(priors=None, var_smoothing=1e-09)

In [80]:
model.predict([[0.2,1,2,1]])

array([1])

In [84]:
expected=dataset.target
predicted=model.predict(dataset.data)

In [87]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))
print(metrics.accuracy_score(expected,predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
0.96
